### ISSUE TITLE
Nice job + Any insights you can share?

### ISSUE THREAD

**Issue by azzarelli** [lif314/X-KANeRF#3]
Thank you for the deeper model comparisons and results!
I was doing some playing about with KANeRF architectures (on my own) and was struggling to get decent results and low training time, so this is super helpful for knowing whether they can be applied.

I was wondering if we can expect other tests in the paper and/or whether there are any other cool insights you could share about KAN-based architectures? For instance, KAN seems to be good at overfitting scenes - might this work better for sparse-view scenes?

~ I acknowledge that you probably want to keep some details for the paper, so I hope I'm not being too nosy ~

**Comment by lif314** [comment]
> Thank you for the deeper model comparisons and results! I was doing some playing about with KANeRF architectures (on my own) and was struggling to get decent results and low training time, so this is super helpful for knowing whether they can be applied.
> 
> I was wondering if we can expect other tests in the paper and/or whether there are any other cool insights you could share about KAN-based architectures? For instance, KAN seems to be good at overfitting scenes - might this work better for sparse-view scenes?
> 
> ~ I acknowledge that you probably want to keep some details for the paper, so I hope I'm not being too nosy ~

Thank you for your interest in my work! In terms of architecture, I kept it consistent with MLP-based NeRF and did not do much design. In fact, I am currently also stuck in the training time and optimization strategy of KAN (such as initialization strategy and optimizer selection). It was previously found that the characteristics of KANeRF cannot support a `paper`. Sorry for the misunderstanding, I deleted the statement of `paper` from the readme.

**Comment by azzarelli** [comment]
I see. Thank you for your reply!. Hopefully we can see the KAN architecture/code evolve to something more interpretable for us :)
